version: '3.8'

services:
  frontend:
    image: "frontend"
    hostname: "frontend"
    container_name: "frontend"
    environment:
      - PORT=3000
    build: 
      context: ./client
    ports:
      - 80:3000
    labels:
      kompose.service.type: LoadBalancer
      kompose.image-pull-policy: "Never"
  backend:
    image: "backend"
    hostname: "backend"
    container_name: "backend"
    environment:
      - PORT=80
    build: 
      context: ./server
    ports:
      - 5001:80